### PR TITLE
Rename key to custom_curl_opts

### PR DESCRIPTION
**Pull request by WardsParadox**
A continuation of #112

### CODE REVIEW

**Comment by grahampugh** [comment]
I'll merge in the changes. I guess the key should ideally be added to the `input_variables` dict of all the processors, but that would mean everyone having to update their overrides, so I'll leave it be.

**Comment by WardsParadox** [comment]
They could also add it via preferences which would allow folks to add custom opts, enter it via the key value `under` run or use a pre-processor to add it without modifying recipes or overrides.

**Comment by grahampugh** [comment]
Yes of course, it's only to properly document the available keys.

**Comment by grahampugh** [comment]
@WardsParadox did you ever try this out? I just tried to use it like this:

```
--key custom_curl_opts="['--max-time', '3600']"
```

But this gets garbled. I'm just wondering how you were passing the options in a format that it liked?

**Pull request merged**
