### PR TITLE
Include Icon Path in Summary Result

### PR DESCRIPTION
**Pull request by MLBZ521**
I have a wrapper around my `autopkg run`'s and I have a use for the icon's path in that post logic.  The value is already known during the Processor run, this change will simply include the `policy_icon_path` value in the `jamfpolicyuploader_summary_results` key so that it can be extracted easily.

### CODE REVIEW

**Comment by MLBZ521** [comment]
Hey Graham, I have updated this PR to match the current code base and after looking at the code a second time....I see it could be greatly simplified, so I have done that.

If you would be willing to merge this, I could stop running a customized version finally.  😁

**Comment by grahampugh** [comment]
Hi, you'll need to look at the Refactor branch I'm afraid. I moved all the functions of each processor into "Base" processors to avoid so many trust-updates in the future.

**Comment by MLBZ521** [comment]
Ah, I merged the latest changes in main into this old branch.   I don't see a "refactor" branch....unless I'm missing something..?

**Comment by grahampugh** [comment]
Oh yes, I forgot that I merged the branch to main already! Cool, then it's easy. I should be able to take a look tomorrow.

**Comment by MLBZ521** [comment]
Thank you sir!

**Pull request merged**
